image:
  repository: 
  tag: 

deployment:
  replicas: 1
  port:  
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

env: []

volumes: []

hpa:
  enabled: false
  replicas:
    min:
    max:
  utilization:
    cpu:
    memory:

ingress:
  enabled: false
  hosts:
    - www.tylerpitcher.com
    - tylerpitcher.com
  path: /
  tlsSecretName: tylerpitcher-tls
  httpsRedirectMiddleware: https-redirect
