image:
  repository: 
  tag: latest

deployment:
  replicas: 1
  port:  

ingress:
  hosts:
    - www.tylerpitcher.com
    - tylerpitcher.com
  path: /
  tlsSecretName: tls-secret
  httpsRedirectMiddleware: https-redirect
