apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.deployment.port }}
          {{- with .Values.deployment.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.env }}
          env:
            {{- range . }}
            - name: {{ .name }}
              {{- if .value }}
              value: {{ .value | quote }}
              {{- else if .valueFrom }}
              valueFrom:
                {{- toYaml .valueFrom | nindent 16 }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- with .Values.volumes }}
          volumeMounts:
            {{- range . }}
            - name: {{ .id }}
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              {{- if .readOnly }}
              readOnly: true
              {{- end }}
            {{- end }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- range . }}
        - name: {{ .id }}
          {{- if eq .type "pvc" }}
          persistentVolumeClaim:
            claimName: {{ .pvc }}
          {{- else if eq .type "emptyDir" }}
          emptyDir: {}
          {{- else if eq .type "configMap" }}
          configMap:
            name: {{ .configMap }}
          {{- else if eq .type "secret" }}
          secret:
            secretName: {{ .secret }}
          {{- end }}
        {{- end }}
      {{- end }}
