{{- if .Values.ingress.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: {{ include "ingress.hostMatcher" . }} && PathPrefix(`{{ .Values.ingress.path }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-service
          port: {{ .Values.deployment.port }}
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress-http
spec:
  entryPoints:
    - web
  routes:
    - match: {{ include "ingress.hostMatcher" . }} && PathPrefix(`{{ .Values.ingress.path }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-service
          port: {{ .Values.deployment.port }}
      middlewares:
        - name: {{ .Values.ingress.httpsRedirectMiddleware }}
{{- end }}
