apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress-https
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`tylerpitcher.com`, `www.tylerpitcher.com`) && PathPrefix(`{{ .Values.route.path }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-service
          port: {{ .Values.deployment.port }}
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ingress-http
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`tylerpitcher.com`, `www.tylerpitcher.com`) && PathPrefix(`{{ .Values.route.path }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-service
          port: {{ .Values.deployment.port }}
      middlewares:
        - name: {{ .Values.ingress.httpsRedirectMiddleware }}
