name: Noteable Changes

on:
  release:
    types:
      - created

jobs:
  update-notes:
    uses: tylerpitcher/github-actions/.github/workflows/noteable.yaml@main
    secrets:
      GIT_PAT: ${{ secrets.GIT_PAT }}
